version: 2
updates:
  # NuGet config for 'EntraMfaPrefillinator.Lib'
  - package-ecosystem: "nuget"
    directory: "/src/Lib"
    target-branch: "main"
    schedule:
      interval: "daily"
    assignees:
      - "Smalls1652"
  
  # NuGet config for 'EntraMfaPrefillinator.AuthUpdateApp'
  - package-ecosystem: "nuget"
    directory: "/src/AuthUpdateApp"
    target-branch: "main"
    ignore:
      - dependency-name: "Azure.Storage.Queues"
      - dependency-name: "Microsoft.Identity.Client"
    schedule:
      interval: "daily"
    assignees:
      - "Smalls1652"

  # NuGet config for 'EntraMfaPrefillinator.Tools.CsvImporter'
  - package-ecosystem: "nuget"
    directory: "/src/Tools/CsvImporter"
    target-branch: "main"
    ignore:
      - dependency-name: "Azure.Storage.Queues"
      - dependency-name: "Microsoft.Identity.Client"
    schedule:
      interval: "daily"
    assignees:
      - "Smalls1652"

  # GitHub Actions config for the repo
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "daily"
    assignees:
      - "Smalls1652"
